platform :ios, '9.0'
 
target ‘Class-Box’ do

pod 'MBProgressHUD'

pod 'MJExtension'

pod 'AFNetworking'

pod 'SDWebImage'

pod 'MBProgressHUD'

pod 'Masonry', '1.0.2'

pod 'HXWeiboPhotoPicker'

pod 'MJRefresh'

pod 'YYCache'

end
